### ISSUE TITLE
Reconnect issue

### ISSUE THREAD

**Issue by HIMjack666** [mitchwongho/ESP-Alerts-for-Android#6]
At the first connection all fine, got messages like this:
`01:12:38.661 -> onWrite() {uuid=8d8218b6-97bc-4527-a8db-13094ac06b1d,len=51}`
`01:13:28.575 -> onWrite() {uuid=8d8218b6-97bc-4527-a8db-13094ac06b1d,len=47}`
then connection lost... reconnect
`01:13:57.150 -> LE onDisconnect`
`01:14:12.476 -> LE onConnect`
connection established, but notifications all are cutted to 20 letters:
`01:14:25.725 -> onWrite() {uuid=8d8218b6-97bc-4527-a8db-13094ac06b1d,len=20}`
`01:30:12.858 -> onWrite() {uuid=8d8218b6-97bc-4527-a8db-13094ac06b1d,len=20}`

Kill & Start service in application resolving problem, but it`s not good variant

**Comment by Petros144** [comment]
Set MTU Size to Static 265 bytes on declaration: 
after ble init

BLEDevice::setMTU(256); //<<<< MTU SIZE

some android devicees only do 20bytes on start up somehow?! this works for me

**Comment by HIMjack666** [comment]
@Petros144 thanks a lot! I will try do that

**Comment by HIMjack666** [comment]
> Set MTU Size to Static 265 bytes on declaration:
> after ble init
> 
> BLEDevice::setMTU(256); //<<<< MTU SIZE
> 
> some android devicees only do 20bytes on start up somehow?! this works for me


works perfect!
