### ISSUE TITLE
 length always 20 

### ISSUE THREAD

**Issue by kitsunex3** [mitchwongho/ESP-Alerts-for-Android#9]
onWrite() {uuid=8d8218b6-97bc-4527-a8db-13094ac06b1d,len=20}
Magpie:"Caribou" via
onWrite() {uuid=8d8218b6-97bc-4527-a8db-13094ac06b1d,len=20}
Magpie:"Caribou" via

this is the serial  output ,  the  LEN  is always 20 resulting  in  only 20 chars of the string being displayed on the screen ,   not sure  is it's my phone only sending 20 or  a bug  

please help  , i  used the API  in the "  getting started " part  here

**Comment by HIMjack666** [comment]
https://github.com/mitchwongho/ESP-Alerts-for-Android/issues/6

**Comment by kitsunex3** [comment]
is this in the android code or the arduino code ? 

i can do arduino but building the app  i cant  , i'll have to ask a frind to  edit this and build the APK for me 
or if you want to  .

**Comment by HIMjack666** [comment]
> is this in the android code or the arduino code ?
> 
> i can do arduino but building the app i cant , i'll have to ask a frind to edit this and build the APK for me
> or if you want to .

Code for Arduino, add this line in setup in sketch:

BLEDevice::setMTU(256); //<<<< MTU SIZE

**Comment by kitsunex3** [comment]
no this did not  solve the issue 
addet it here 

void setupBLEServer() {
  //init BLE server
  
  BLEDevice::init("badge");
  BLEDevice::setMTU(517);

 i chose  517 cus apperently it's the max mtu a esp32 can  handle 
 taking your  256   also does not go  , there it just disconnects  the ble  and reconnects

**Comment by kitsunex3** [comment]
might be related 

https://forum.developer.samsung.com/t/samsung-android-10-ble-connectivity-regression/509

**Comment by kitsunex3** [comment]
so random question what type of phone do you have

**Comment by HIMjack666** [comment]
> so random question what type of phone do you have

HTC M8, M10, Xiaomi Redmi 5 all fine.

Also works good with MTU 128.

**Comment by kitsunex3** [comment]
just tested with my  old one plus 2  
works like a charm  ,  so it's a phone related issue 

to bad 

thanks for the help
